class Waveform:

    def __init__(
        self,
        voltage: float,
        duration: float = 1.0
    ):
        self.ideal_voltage = voltage      # Generated by encoder
        self.voltage = voltage            # Current voltage after channel effects

        self.frequency = None             # For FSK later
        self.phase = None                 # For PSK later
        self.samples = []

    def __repr__(self):

        return (
            f"Waveform("
            f"voltage={self.voltage}, "
            f"duration={self.duration})"
        )